<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'DoctrineNamespaceCacheKey%5B%5D' => 0,
'%5BApp%5CEntity%5CAdmin%24CLASSMETADATA%5D%5B1%5D' => 1,
'%5BApp%5CEntity%5CAvisClient%24CLASSMETADATA%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCategorie%24CLASSMETADATA%5D%5B1%5D' => 3,
'%5BApp%5CEntity%5CCategorief%24CLASSMETADATA%5D%5B1%5D' => 4,
'%5BApp%5CEntity%5CChat%24CLASSMETADATA%5D%5B1%5D' => 5,
'%5BApp%5CEntity%5CCinema%24CLASSMETADATA%5D%5B1%5D' => 6,
'%5BApp%5CEntity%5CConge%24CLASSMETADATA%5D%5B1%5D' => 7,
'%5BApp%5CEntity%5CDemandeRes%24CLASSMETADATA%5D%5B1%5D' => 8,
'%5BApp%5CEntity%5Cemploye%24CLASSMETADATA%5D%5B1%5D' => 9,
'%5BApp%5CEntity%5CEvenement%24CLASSMETADATA%5D%5B1%5D' => 10,
'%5BApp%5CEntity%5CFilm%24CLASSMETADATA%5D%5B1%5D' => 11,
'%5BApp%5CEntity%5CGuide%24CLASSMETADATA%5D%5B1%5D' => 12,
'%5BApp%5CEntity%5CPlat%24CLASSMETADATA%5D%5B1%5D' => 13,
'%5BApp%5CEntity%5CReclamation%24CLASSMETADATA%5D%5B1%5D' => 14,
'%5BApp%5CEntity%5CUser%24CLASSMETADATA%5D%5B1%5D' => 15,

], [

0 => 'N;',
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Admin',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Admin',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdminRepository',
                ],
                'identifier' => [
                    [
                        'idadmin',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'idadmin' => [
                            'fieldName' => 'idadmin',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'idadmin',
                        ],
                        'emailadmin' => [
                            'fieldName' => 'emailadmin',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'emailadmin',
                        ],
                        'pwdadmin' => [
                            'fieldName' => 'pwdadmin',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'pwdadmin',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idadmin' => 'idadmin',
                        'emailadmin' => 'emailadmin',
                        'pwdadmin' => 'pwdadmin',
                    ],
                ],
                'columnNames' => [
                    [
                        'idadmin' => 'idadmin',
                        'emailadmin' => 'emailadmin',
                        'pwdadmin' => 'pwdadmin',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'admin',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\AvisClient',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AvisClient',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AvisClientRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'rating' => [
                            'fieldName' => 'rating',
                            'type' => 'float',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'rating',
                        ],
                        'descR' => [
                            'fieldName' => 'descR',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'desc_r',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'rating' => 'rating',
                        'desc_r' => 'descR',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'rating' => 'rating',
                        'descR' => 'desc_r',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'avis_client',
                    ],
                ],
                'associationMappings' => [
                    [
                        'idRclient' => [
                            'fieldName' => 'idRclient',
                            'joinColumns' => [
                                [
                                    'name' => 'User',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\User',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\AvisClient',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'User' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'User' => 'User',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'User',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Categorie',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Categorie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CategorieRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'id_categorie' => [
                            'fieldName' => 'id_categorie',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_categorie',
                        ],
                        'nom_categorie' => [
                            'fieldName' => 'nom_categorie',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_categorie',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_categorie' => 'id_categorie',
                        'nom_categorie' => 'nom_categorie',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'id_categorie' => 'id_categorie',
                        'nom_categorie' => 'nom_categorie',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'categorie',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Categorief',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Categorief',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CategoriefRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'descC' => [
                            'fieldName' => 'descC',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'desc_c',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'desc_c' => 'descC',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'descC' => 'desc_c',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'categorief',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Chat',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Chat',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ChatRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'id_chat' => [
                            'fieldName' => 'id_chat',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_chat',
                        ],
                        'idsender' => [
                            'fieldName' => 'idsender',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'idsender',
                        ],
                        'idreceiver' => [
                            'fieldName' => 'idreceiver',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'idreceiver',
                        ],
                        'msg' => [
                            'fieldName' => 'msg',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'msg',
                        ],
                        'time' => [
                            'fieldName' => 'time',
                            'type' => 'time',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'time',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_chat' => 'id_chat',
                        'idsender' => 'idsender',
                        'idreceiver' => 'idreceiver',
                        'msg' => 'msg',
                        'time' => 'time',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'id_chat' => 'id_chat',
                        'idsender' => 'idsender',
                        'idreceiver' => 'idreceiver',
                        'msg' => 'msg',
                        'time' => 'time',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'chat',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Cinema',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Cinema',
                ],
                'identifier' => [
                    [
                        'num',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'num' => [
                            'fieldName' => 'num',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'num',
                            'id' => true,
                        ],
                        'date' => [
                            'fieldName' => 'date',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'date',
                        ],
                        'nbr' => [
                            'fieldName' => 'nbr',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nbr',
                        ],
                        'heurep' => [
                            'fieldName' => 'heurep',
                            'type' => 'time',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'heurep',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'num' => 'num',
                        'date' => 'date',
                        'nbr' => 'nbr',
                        'heurep' => 'heurep',
                    ],
                ],
                'columnNames' => [
                    [
                        'num' => 'num',
                        'date' => 'date',
                        'nbr' => 'nbr',
                        'heurep' => 'heurep',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'cinema',
                    ],
                ],
                'associationMappings' => [
                    [
                        'film' => [
                            'fieldName' => 'film',
                            'joinColumns' => [
                                [
                                    'name' => 'film',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id_film',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Film',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Cinema',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'film' => 'id_film',
                            ],
                            'joinColumnFieldNames' => [
                                'film' => 'film',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id_film' => 'film',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Conge',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Conge',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CongeRepository',
                ],
                'identifier' => [
                    [
                        'idconge',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'idconge' => [
                            'fieldName' => 'idconge',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'idconge',
                        ],
                        'dateconge' => [
                            'fieldName' => 'dateconge',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'dateconge',
                        ],
                        'motifconge' => [
                            'fieldName' => 'motifconge',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'motifconge',
                        ],
                        'nbjourconge' => [
                            'fieldName' => 'nbjourconge',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nbjourconge',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idconge' => 'idconge',
                        'dateconge' => 'dateconge',
                        'motifconge' => 'motifconge',
                        'nbjourconge' => 'nbjourconge',
                    ],
                ],
                'columnNames' => [
                    [
                        'idconge' => 'idconge',
                        'dateconge' => 'dateconge',
                        'motifconge' => 'motifconge',
                        'nbjourconge' => 'nbjourconge',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'conge',
                    ],
                ],
                'associationMappings' => [
                    [
                        'employe' => [
                            'fieldName' => 'employe',
                            'joinColumns' => [
                                [
                                    'name' => 'employe_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'idemp',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'conges',
                            'targetEntity' => 'App\\Entity\\employe',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Conge',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'employe_id' => 'idemp',
                            ],
                            'joinColumnFieldNames' => [
                                'employe_id' => 'employe_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'idemp' => 'employe_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\DemandeRes',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\DemandeRes',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\DemandeResRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'reference' => [
                            'fieldName' => 'reference',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'reference',
                        ],
                        'id_client' => [
                            'fieldName' => 'id_client',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_client',
                        ],
                        'matricule' => [
                            'fieldName' => 'matricule',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'matricule',
                        ],
                        'nom_client' => [
                            'fieldName' => 'nom_client',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_client',
                        ],
                        'prenom_client' => [
                            'fieldName' => 'prenom_client',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'prenom_client',
                        ],
                        'date' => [
                            'fieldName' => 'date',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'date',
                        ],
                        'duree' => [
                            'fieldName' => 'duree',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'duree',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'reference' => 'reference',
                        'id_client' => 'id_client',
                        'matricule' => 'matricule',
                        'nom_client' => 'nom_client',
                        'prenom_client' => 'prenom_client',
                        'date' => 'date',
                        'duree' => 'duree',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'reference' => 'reference',
                        'id_client' => 'id_client',
                        'matricule' => 'matricule',
                        'nom_client' => 'nom_client',
                        'prenom_client' => 'prenom_client',
                        'date' => 'date',
                        'duree' => 'duree',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'demande_res',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\employe',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\employe',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\EmployeRepository',
                ],
                'identifier' => [
                    [
                        'idemp',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'idemp' => [
                            'fieldName' => 'idemp',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'idemp',
                        ],
                        'nomemp' => [
                            'fieldName' => 'nomemp',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nomemp',
                        ],
                        'prenomemp' => [
                            'fieldName' => 'prenomemp',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'prenomemp',
                        ],
                        'numtelemp' => [
                            'fieldName' => 'numtelemp',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'numtelemp',
                        ],
                        'adresseemp' => [
                            'fieldName' => 'adresseemp',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'adresseemp',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idemp' => 'idemp',
                        'nomemp' => 'nomemp',
                        'prenomemp' => 'prenomemp',
                        'numtelemp' => 'numtelemp',
                        'adresseemp' => 'adresseemp',
                    ],
                ],
                'columnNames' => [
                    [
                        'idemp' => 'idemp',
                        'nomemp' => 'nomemp',
                        'prenomemp' => 'prenomemp',
                        'numtelemp' => 'numtelemp',
                        'adresseemp' => 'adresseemp',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'employe',
                    ],
                ],
                'associationMappings' => [
                    [
                        'conges' => [
                            'fieldName' => 'conges',
                            'mappedBy' => 'employe',
                            'targetEntity' => 'App\\Entity\\Conge',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\employe',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Evenement',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Evenement',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\EvenementRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'id_event' => [
                            'fieldName' => 'id_event',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_event',
                        ],
                        'nom_event' => [
                            'fieldName' => 'nom_event',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_event',
                        ],
                        'date_event' => [
                            'fieldName' => 'date_event',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'date_event',
                        ],
                        'date_event_fin' => [
                            'fieldName' => 'date_event_fin',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'date_event_fin',
                        ],
                        'capacite' => [
                            'fieldName' => 'capacite',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'capacite',
                        ],
                        'emplacement' => [
                            'fieldName' => 'emplacement',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'emplacement',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_event' => 'id_event',
                        'nom_event' => 'nom_event',
                        'date_event' => 'date_event',
                        'date_event_fin' => 'date_event_fin',
                        'capacite' => 'capacite',
                        'emplacement' => 'emplacement',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'id_event' => 'id_event',
                        'nom_event' => 'nom_event',
                        'date_event' => 'date_event',
                        'date_event_fin' => 'date_event_fin',
                        'capacite' => 'capacite',
                        'emplacement' => 'emplacement',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'evenement',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Film',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Film',
                ],
                'identifier' => [
                    [
                        'id_film',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id_film' => [
                            'fieldName' => 'id_film',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id_film',
                        ],
                        'nomFilm' => [
                            'fieldName' => 'nomFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nomFilm',
                        ],
                        'dateSortie' => [
                            'fieldName' => 'dateSortie',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'datesortie',
                        ],
                        'descriptionf' => [
                            'fieldName' => 'descriptionf',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'descriptionf',
                        ],
                        'filename' => [
                            'fieldName' => 'filename',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'filename',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id_film' => 'id_film',
                        'nomFilm' => 'nomFilm',
                        'datesortie' => 'dateSortie',
                        'descriptionf' => 'descriptionf',
                        'filename' => 'filename',
                    ],
                ],
                'columnNames' => [
                    [
                        'id_film' => 'id_film',
                        'nomFilm' => 'nomFilm',
                        'dateSortie' => 'datesortie',
                        'descriptionf' => 'descriptionf',
                        'filename' => 'filename',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'film',
                    ],
                ],
                'associationMappings' => [
                    [
                        'categorie' => [
                            'fieldName' => 'categorie',
                            'targetEntity' => 'App\\Entity\\Categorief',
                            'joinColumns' => [
                                [
                                    'name' => 'categorie',
                                    'unique' => true,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'mappedBy' => null,
                            'inversedBy' => null,
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 1,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Film',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'categorie' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'categorie' => 'categorie',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'categorie',
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Guide',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Guide',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\GuideRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'id_guide' => [
                            'fieldName' => 'id_guide',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_guide',
                        ],
                        'nom_guide' => [
                            'fieldName' => 'nom_guide',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_guide',
                        ],
                        'prenom_guide' => [
                            'fieldName' => 'prenom_guide',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'prenom_guide',
                        ],
                        'activite' => [
                            'fieldName' => 'activite',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'activite',
                        ],
                        'agenda' => [
                            'fieldName' => 'agenda',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'agenda',
                        ],
                        'agenda_time' => [
                            'fieldName' => 'agenda_time',
                            'type' => 'time',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'agenda_time',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_guide' => 'id_guide',
                        'nom_guide' => 'nom_guide',
                        'prenom_guide' => 'prenom_guide',
                        'activite' => 'activite',
                        'agenda' => 'agenda',
                        'agenda_time' => 'agenda_time',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'id_guide' => 'id_guide',
                        'nom_guide' => 'nom_guide',
                        'prenom_guide' => 'prenom_guide',
                        'activite' => 'activite',
                        'agenda' => 'agenda',
                        'agenda_time' => 'agenda_time',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'guide',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Plat',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Plat',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PlatRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'id_plat' => [
                            'fieldName' => 'id_plat',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_plat',
                        ],
                        'nom_plat' => [
                            'fieldName' => 'nom_plat',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_plat',
                        ],
                        'description_plat' => [
                            'fieldName' => 'description_plat',
                            'type' => 'text',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'description_plat',
                        ],
                        'prix_plat' => [
                            'fieldName' => 'prix_plat',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'prix_plat',
                        ],
                        'categorie_plat' => [
                            'fieldName' => 'categorie_plat',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'categorie_plat',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_plat' => 'id_plat',
                        'nom_plat' => 'nom_plat',
                        'description_plat' => 'description_plat',
                        'prix_plat' => 'prix_plat',
                        'categorie_plat' => 'categorie_plat',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'id_plat' => 'id_plat',
                        'nom_plat' => 'nom_plat',
                        'description_plat' => 'description_plat',
                        'prix_plat' => 'prix_plat',
                        'categorie_plat' => 'categorie_plat',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'plat',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Reclamation',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Reclamation',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ReclamationRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'id_rec' => [
                            'fieldName' => 'id_rec',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'id_rec',
                        ],
                        'description' => [
                            'fieldName' => 'description',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'description',
                        ],
                        'date_rec' => [
                            'fieldName' => 'date_rec',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'date_rec',
                        ],
                        'field' => [
                            'fieldName' => 'field',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'field',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'id_rec' => 'id_rec',
                        'description' => 'description',
                        'date_rec' => 'date_rec',
                        'field' => 'field',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'id_rec' => 'id_rec',
                        'description' => 'description',
                        'date_rec' => 'date_rec',
                        'field' => 'field',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'reclamation',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\User',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'email' => [
                            'fieldName' => 'email',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 180,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'email',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'json',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'roles',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'password',
                        ],
                        'lastname' => [
                            'fieldName' => 'lastname',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'lastname',
                        ],
                        'isVerified' => [
                            'fieldName' => 'isVerified',
                            'type' => 'boolean',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'is_verified',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                        'lastname' => 'lastname',
                        'is_verified' => 'isVerified',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                        'lastname' => 'lastname',
                        'isVerified' => 'is_verified',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
