<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYUmgjoK\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYUmgjoK/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYUmgjoK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYUmgjoK\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerYUmgjoK\srcApp_KernelProdContainer([
    'container.build_hash' => 'YUmgjoK',
    'container.build_id' => 'f343efb4',
    'container.build_time' => 1617023784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYUmgjoK');
