<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Abonne extends \App\Entity\Abonne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'nomabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'prenomabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'mailabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'datenaissabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'telephoneabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'password', 'confirm_password', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'abonnements', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'stripeid'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'nomabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'prenomabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'mailabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'datenaissabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'telephoneabonne', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'password', 'confirm_password', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'abonnements', '' . "\0" . 'App\\Entity\\Abonne' . "\0" . 'stripeid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Abonne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomabonne(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomabonne', []);

        return parent::getNomabonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomabonne(string $nomabonne): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomabonne', [$nomabonne]);

        return parent::setNomabonne($nomabonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomabonne(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomabonne', []);

        return parent::getPrenomabonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomabonne(string $prenomabonne): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomabonne', [$prenomabonne]);

        return parent::setPrenomabonne($prenomabonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailabonne(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailabonne', []);

        return parent::getMailabonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailabonne(string $mailabonne): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailabonne', [$mailabonne]);

        return parent::setMailabonne($mailabonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaissabonne(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaissabonne', []);

        return parent::getDatenaissabonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaissabonne(\DateTimeInterface $datenaissabonne): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaissabonne', [$datenaissabonne]);

        return parent::setDatenaissabonne($datenaissabonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneabonne(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneabonne', []);

        return parent::getTelephoneabonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneabonne(int $telephoneabonne): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneabonne', [$telephoneabonne]);

        return parent::setTelephoneabonne($telephoneabonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(string $roles): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getStripeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStripeid', []);

        return parent::getStripeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setStripeid(string $stripeid): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStripeid', [$stripeid]);

        return parent::setStripeid($stripeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbonnements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbonnements', []);

        return parent::getAbonnements();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbonnement(\App\Entity\Abonnement $abonnement): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbonnement', [$abonnement]);

        return parent::addAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbonnement(\App\Entity\Abonnement $abonnement): \App\Entity\Abonne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbonnement', [$abonnement]);

        return parent::removeAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
