<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKSPvzc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKSPvzc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKSPvzc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKSPvzc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNKSPvzc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NKSPvzc',
    'container.build_id' => '2d2ad1f0',
    'container.build_time' => 1650634962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKSPvzc');
